In [1]:
import numpy as np
import pandas as pd

In [2]:
ser = pd.Series(np.random.random(5),name='Column 01')

In [3]:
ser

0    0.698563
1    0.489342
2    0.846018
3    0.013598
4    0.104748
Name: Column 01, dtype: float64

In [4]:
ser[2]

0.8460183975833061

In [17]:
from pandas_datareader import data as wb
import datetime

In [26]:
start = datetime(2017,1,1)#获取数据的时间段-起始时间

In [30]:
end = datetime.today()

In [40]:
PG = wb.DataReader('PG',data_source = 'yahoo',start = '1995-01-01')

In [41]:
PG

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
1995-01-03,15.625000,15.437500,15.468750,15.593750,3318400.0,6.400181
1995-01-04,15.656250,15.312500,15.531250,15.468750,2218800.0,6.348878
1995-01-05,15.437500,15.218750,15.375000,15.250000,2319600.0,6.259093
1995-01-06,15.406250,15.156250,15.156250,15.281250,3438000.0,6.271922
1995-01-09,15.406250,15.187500,15.343750,15.218750,1795200.0,6.246270
1995-01-10,15.437500,15.187500,15.281250,15.406250,4364000.0,6.323225
1995-01-11,15.593750,15.375000,15.593750,15.375000,3738400.0,6.310401
1995-01-12,15.531250,15.312500,15.375000,15.531250,3307600.0,6.374530
1995-01-13,15.843750,15.531250,15.593750,15.625000,3992800.0,6.560857
1995-01-16,15.968750,15.750000,15.906250,15.750000,3677200.0,6.613344
1995-01-17,15.812500,15.656250,15.718750,15.812500,2437600.0,6.639586
1995-01-18,15.750000,15.437500,15.687500,15.468750,3535200.0,6.495250
1995-01-19,15.406250,15.343750,15.343750,15.406250,2491200.0,6.469004
1995-01-20,15.406250,15.250000,15.406250,15.343750,5130800.0,6.442760
1995-01-23,15.500000,15.187500,15.187500,15.500000,3147200.0,6.508373
1995-01-24,15.531250,15.375000,15.500000,15.468750,2016400.0,6.495250
1995-01-25,15.781250,15.437500,15.500000,15.687500,2802400.0,6.587102
1995-01-26,15.843750,15.687500,15.718750,15.750000,3124000.0,6.613344
1995-01-27,16.250000,15.812500,15.812500,16.187500,6247200.0,6.797049
1995-01-30,16.562500,16.093750,16.125000,16.437500,5226400.0,6.902022
1995-01-31,16.500000,16.281250,16.343750,16.281250,3934800.0,6.836417
1995-02-01,16.343750,15.937500,16.343750,15.968750,3047200.0,6.705199
1995-02-02,16.125000,15.875000,15.968750,16.093750,3810400.0,6.757686
1995-02-03,16.375000,16.187500,16.218750,16.250000,4442800.0,6.823295
1995-02-06,16.625000,16.281250,16.281250,16.625000,4003600.0,6.980753
1995-02-07,16.593750,16.406250,16.562500,16.593750,2380400.0,6.967631
1995-02-08,16.593750,16.406250,16.593750,16.406250,2481200.0,6.888901
1995-02-09,16.468750,16.312500,16.437500,16.375000,2143600.0,6.875778
1995-02-10,16.406250,16.156250,16.343750,16.343750,2445600.0,6.862661
1995-02-13,16.468750,16.312500,16.312500,16.468750,1726400.0,6.915147
...,...,...,...,...,...,...
2019-11-20,122.379997,120.930000,121.419998,122.290001,6480000.0,122.290001
2019-11-21,122.540001,120.279999,121.779999,120.339996,7094100.0,120.339996
2019-11-22,120.610001,119.389999,120.230003,120.290001,4414900.0,120.290001
2019-11-25,120.919998,120.019997,120.440002,120.510002,5134300.0,120.510002
2019-11-26,122.349998,120.410004,120.730003,122.260002,8235200.0,122.260002
2019-11-27,122.440002,120.959999,122.419998,121.760002,3751400.0,121.760002
2019-11-29,122.629997,121.709999,121.989998,122.059998,2927300.0,122.059998
2019-12-02,122.779999,120.959999,121.940002,122.720001,6146200.0,122.720001
2019-12-03,122.959999,121.800003,122.309998,122.949997,6396200.0,122.949997
2019-12-04,124.580002,122.690002,122.750000,124.529999,6857300.0,124.529999
2019-12-05,124.629997,123.660004,124.269997,124.620003,7029200.0,124.620003
2019-12-06,125.449997,123.889999,124.730003,124.190002,7150900.0,124.190002
2019-12-09,125.139999,124.180000,124.309998,124.870003,7452800.0,124.870003
2019-12-10,124.870003,124.120003,124.779999,124.269997,4740100.0,124.269997
2019-12-11,125.269997,124.070000,124.269997,124.660004,4823300.0,124.660004
2019-12-12,125.760002,123.879997,124.779999,124.570000,5897800.0,124.570000
2019-12-13,125.739998,123.790001,124.209999,125.470001,5471600.0,125.470001
2019-12-16,126.349998,125.349998,125.470001,125.559998,8281900.0,125.559998
2019-12-17,125.980003,124.309998,125.589996,125.309998,8832200.0,125.309998
2019-12-18,125.870003,123.690002,125.309998,124.010002,8607600.0,124.010002
2019-12-19,125.199997,123.900002,124.160004,124.919998,6629100.0,124.919998
2019-12-20,126.599998,125.029999,126.150002,125.360001,16250500.0,125.360001
2019-12-23,125.820000,124.690002,125.519997,124.900002,6619500.0,124.900002
2019-12-24,125.309998,124.580002,124.790001,125.220001,2022100.0,125.220001
2019-12-26,125.750000,124.870003,125.099998,125.220001,4760400.0,125.220001
2019-12-27,126.300003,125.389999,125.559998,126.089996,5192000.0,126.089996
2019-12-30,125.980003,124.139999,125.760002,124.470001,3884300.0,124.470001
2019-12-31,124.989998,123.949997,124.430000,124.900002,4798900.0,124.900002
2020-01-02,124.730003,122.940002,124.500000,123.410004,8130800.0,123.410004
2020-01-03,123.529999,121.860001,122.160004,122.580002,7970500.0,122.580002

In [35]:
stock = wb.DataReader("600797.SS", "yahoo", start, end)

In [36]:
stock

                 High        Low       Open      Close      Volume  Adj Close
Date
2017-01-03  18.000000  18.000000  18.000000  18.000000         0.0  17.806698
2017-01-04  18.000000  18.000000  18.000000  18.000000         0.0  17.806698
2017-01-05  18.000000  18.000000  18.000000  18.000000         0.0  17.806698
2017-01-06  17.950001  16.200001  17.950001  16.200001  31539335.0  16.026030
2017-01-09  16.180000  14.900000  15.500000  15.420000  31874588.0  15.254406
2017-01-10  15.720000  15.000000  15.300000  15.220000  17978484.0  15.056554
2017-01-11  15.240000  14.930000  15.110000  15.150000  12768693.0  14.987305
2017-01-12  15.170000  14.760000  15.130000  14.780000   9942103.0  14.621278
2017-01-13  14.900000  13.300000  14.790000  13.300000  31130989.0  13.157172
2017-01-16  13.170000  11.970000  13.170000  12.240000  37516238.0  12.108556
2017-01-17  12.850000  12.270000  12.280000  12.830000  23158749.0  12.692220
2017-01-18  12.780000  12.380000  12.720000  12.490000  13788909.0  12.355870
2017-01-19  12.610000  12.180000  12.610000  12.370000  14374475.0  12.237159
2017-01-20  12.600000  12.230000  12.320000  12.490000  17778463.0  12.355870
2017-01-23  12.950000  12.480000  12.500000  12.790000  19366164.0  12.652648
2017-01-24  12.890000  12.630000  12.720000  12.780000  10308033.0  12.642756
2017-01-25  13.350000  12.710000  12.780000  13.280000  19310370.0  13.137386
2017-01-26  13.770000  13.190000  13.220000  13.660000  18178192.0  13.513305
2017-02-03  13.840000  13.510000  13.710000  13.640000  11523995.0  13.493521
2017-02-06  13.930000  13.500000  13.650000  13.820000  13175512.0  13.671588
2017-02-07  13.960000  13.650000  13.810000  13.760000  10437812.0  13.612232
2017-02-08  13.750000  13.360000  13.750000  13.650000  13974384.0  13.503413
2017-02-09  13.840000  13.570000  13.660000  13.680000  12607448.0  13.533092
2017-02-10  13.850000  13.570000  13.710000  13.680000  10401205.0  13.533092
2017-02-13  13.700000  13.330000  13.680000  13.470000  14234611.0  13.325346
2017-02-14  13.540000  13.340000  13.460000  13.470000  10918596.0  13.325346
2017-02-15  13.540000  13.150000  13.410000  13.210000  12607002.0  13.068138
2017-02-16  13.290000  13.140000  13.200000  13.230000   8882031.0  13.087923
2017-02-17  13.260000  12.790000  13.220000  12.820000  14103785.0  12.682326
2017-02-20  12.990000  12.700000  12.750000  12.950000   9835878.0  12.810931
...               ...        ...        ...        ...         ...        ...
2019-11-25  10.480000   9.660000  10.480000   9.860000  63585760.0   9.860000
2019-11-26  10.090000   9.800000   9.900000   9.850000  32716711.0   9.850000
2019-11-27  10.020000   9.770000   9.880000   9.910000  36176441.0   9.910000
2019-11-28  10.150000   9.810000   9.840000  10.040000  48504140.0  10.040000
2019-11-29  10.030000   9.810000  10.010000   9.900000  31374362.0   9.900000
2019-12-02   9.960000   9.760000   9.910000   9.790000  29621046.0   9.790000
2019-12-03   9.820000   9.360000   9.660000   9.820000  51216576.0   9.820000
2019-12-04   9.940000   9.670000   9.720000   9.900000  36449995.0   9.900000
2019-12-05  10.140000   9.900000   9.970000  10.010000  53536404.0  10.010000
2019-12-06  10.190000   9.900000  10.010000  10.110000  46830431.0  10.110000
2019-12-09  10.380000   9.990000  10.080000  10.230000  61361748.0  10.230000
2019-12-10  10.230000  10.010000  10.190000  10.150000  43127205.0  10.150000
2019-12-11  10.440000  10.050000  10.130000  10.070000  52621115.0  10.070000
2019-12-12  10.280000   9.960000  10.060000  10.130000  42079859.0  10.130000
2019-12-13  10.300000  10.120000  10.250000  10.270000  45169588.0  10.270000
2019-12-16  10.490000  10.230000  10.320000  10.490000  53276818.0  10.490000
2019-12-17  11.060000  10.400000  10.530000  10.840000  88621071.0  10.840000
2019-12-18  10.950000  10.640000  10.800000  10.650000  59982834.0  10.650000
2019-12-19  10.810000  10.610000  10.640000  10.680000  37632277.0  10.680000
2019-12-20  10.710000  10.230000  10.660000  10.230000  49072396.0  10.230000
2019-12-23  10.260000   9.890000  10.240000   9.910000  38423478.0   9.910000
2019-12-24  10.070000   9.880000   9.980000  10.000000  23831101.0  10.000000
2019-12-25  10.270000   9.970000  10.020000  10.210000  33905191.0  10.210000
2019-12-26  10.290000  10.120000  10.290000  10.220000  25342701.0  10.220000
2019-12-27  10.260000   9.960000  10.200000   9.960000  34929553.0   9.960000
2019-12-30  10.170000   9.590000   9.870000  10.150000  38187327.0  10.150000
2019-12-31  10.210000  10.000000  10.100000  10.070000  25429773.0  10.070000
2020-01-02  10.420000  10.100000  10.170000  10.380000  49332714.0  10.380000
2020-01-03  10.550000  10.290000  10.390000  10.550000  49583005.0  10.550000
2020-01-06  10.680000  10.360000  10.470000  10.510000  52598635.0  10.510000

[732 rows x 6 columns]